config/urls.py
from django import views
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from home.views import principal
from home.views import inicio
from home.views import login
from home.views import cadastro
from home.views import dashboard
from home.views import logout
from home.views import home, form, create, view, edit, update, delete
from home.views import homeproduto, formproduto, createproduto, viewproduto, editproduto, updateproduto, deleteproduto
from home.views import homevenda, formvenda, createvenda, viewvenda, editvenda, updatevenda, deletevenda
from home.views import homeestoque4peca, formestoque4peca, createestoque4peca, viewestoque4peca, editestoque4peca, updateestoque4peca, deleteestoque4peca
from home.views import homeestoque1peca, formestoque1peca, createestoque1peca, viewestoque1peca, editestoque1peca, updateestoque1peca, deleteestoque1peca
from django.contrib import messages, auth
#from home.views import login, logout, index, cadastro, dashboard
from django.contrib.auth.decorators import login_required
#from home.views import search
#from home.views import searchpessoa
#from home.views import searchproduto


urlpatterns = [
   # path('', include('home.urls')),  USAR ESTE MODO COMBINANDO COM O URLS APARTE


    path('admin/', admin.site.urls),
    path('', inicio, name='inicio'),
    path('login/', login, name='login'),
    path('cadastro/', cadastro, name='cadastro'),
    path('logout/', logout, name='logout'),
    path('dashboard/', dashboard, name='dashboard'),
    path('principal/', principal, name='principal'),
#da ma              path('search/',search, name='search'),
#     path('searchpessoa/',searchpessoa, name='searchpessoa'),
#    path('searchproduto/',searchproduto, name='searchproduto'),




                  # URLS CLIENTES
    path('homepessoa/', home, name='home'),
    path('formpessoa/', form, name='form'),
    path('createpessoa/', create, name='create'),
    path('viewpessoa/<int:pk>/', view, name='view'),
    path('editpessoa/<int:pk>/', edit, name='edit'),
    path('updatepessoa/<int:pk>/', update, name='update'),
    path('deletepessoa/<int:pk>/', delete, name='delete'),



                  # URLS PRODUTOS
     path('homeproduto/', homeproduto, name='homeproduto'),
     path('formproduto/', formproduto, name='formproduto'),
     path('createproduto/', createproduto, name='createproduto'),
     path('viewproduto/<int:pk>/', viewproduto, name='viewproduto'),
     path('editproduto/<int:pk>/', editproduto, name='editproduto'),
     path('updateproduto/<int:pk>/', updateproduto, name='updateproduto'),
     path('deleteproduto/<int:pk>/', deleteproduto, name='deleteproduto'),

                # URLS VENDA
     path('homevenda/', homevenda, name='homevenda'),
     path('formvenda/', formvenda, name='formvenda'),
     path('createvenda/', createvenda, name='createvenda'),
     path('viewvenda/<int:pk>/', viewvenda, name='viewvenda'),
     path('editvenda/<int:pk>/', editvenda, name='editvenda'),
     path('updatevenda/<int:pk>/', updatevenda, name='updatevenda'),
     path('deletevenda/<int:pk>/', deletevenda, name='deletevenda'),

                # URLS ESTOQUE 4 PEÇA

    path('homeestoque4peca/', homeestoque4peca, name='homeestoque4peca'),
    path('formestoque4peca/', formestoque4peca, name='formestoque4peca'),
    path('createestoque4peca/', createestoque4peca, name='createestoque4peca'),
    path('viewestoque4peca/<int:pk>/', viewestoque4peca, name='viewestoque4peca'),
    path('editestoque4peca/<int:pk>/', editestoque4peca, name='editestoque4peca'),
    path('updateestoque4peca/<int:pk>/', updateestoque4peca, name='updateestoque4peca'),
    path('deleteestoque4peca/<int:pk>/', deleteestoque4peca, name='deleteestoque4peca'),

                # URLS ESTOQUE 1 PEÇA

    path('homeestoque1peca/', homeestoque1peca, name='homeestoque1peca'),
    path('formestoque1peca/', formestoque1peca, name='formestoque1peca'),
    path('createestoque1peca/', createestoque1peca, name='createestoque1peca'),
    path('viewestoque1peca/<int:pk>/', viewestoque1peca, name='viewestoque1peca'),
    path('editestoque1peca/<int:pk>/', editestoque1peca, name='editestoque1peca'),
    path('updateestoque1peca/<int:pk>/', updateestoque1peca, name='updateestoque1peca'),
    path('deleteestoque1peca/<int:pk>/', deleteestoque1peca, name='deleteestoque1peca'),




] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, patterns, include
from . import views





urlpatterns = [

    path('', views.login, name='index_login'),
    path('inicio/', views.inicio, name='inicio'),
    path('logout/', views.logout, name='logout'),
    path('cadastro/', views.cadastro, name='cadastro'),
    path(r'^search/$', views.search, name='search'),







]

home/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.utils import timezone
from django.db.models import Count
from django.db.models import Max, Min
from datetime import datetime, date


class Pessoa(models.Model):
    nome = models.CharField(max_length=128)
    endereco = models.CharField(max_length=120)
    complemento = models.CharField(max_length=120)
    cep =  models.CharField(max_length=12)
    telefone = models.CharField(max_length=12)
    observacao = models.TextField(blank=True)

    def __str__(self):
        return self.nome


class Produto(models.Model):
    produto = models.CharField(max_length=128)
    vendas = models.ManyToManyField(Pessoa, through='Venda')
    obs = models.TextField(blank=True)
    quantidade = models.PositiveIntegerField(default=1)

    def __str__(self):
        return self.produto

PAGAMENTO = (
    ('Em atendimento', 'Em atendimento'),
    ('A Vista', 'A Vista'),
    ('Pago', 'Pago'),
    ('A Prazo', 'A Prazo'),
    ('Orçamento', 'Orçamento'),
    ('Vencido', 'Vencido'),
    ('Parcelado 3X', 'Parcelado 3X')

)
class Venda(models.Model):
    titulo = models.CharField(max_length=100)
    pessoa = models.ForeignKey(Pessoa, on_delete=models.CASCADE)
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    placa = models.CharField(max_length=128)
    carro = models.CharField(max_length=128)
    data_venda = models.DateTimeField(default=timezone.now)
    preco = models.DecimalField(max_digits=6, decimal_places=2)
    venc_fatura = models.DateField(blank=True, null=True)
    obs = models.TextField(max_length=100)
    pag = models.CharField(max_length=20, choices=PAGAMENTO)

def __str__(self):
        return self.titulo







class Estoque4peca(models.Model):
    produto = models.CharField(max_length=120)
    motorista = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    passageiro = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    assento_esquerdo = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    assento_direito = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    quantidade_em_estoque = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    estoque_minimo = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    obs = models.TextField(blank=True)

    def __str__(self, ):
        return self.produto


class Estoque1peca(models.Model):
    produto = models.CharField(max_length=110)
    quantidade_em_estoque = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    estoque_minimo = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    obs = models.TextField(blank=True)

    def __str__(self, ):
        return self.produto

home/views.py
from django.shortcuts import render, redirect
from home.forms import PessoaForm
from home.forms import ProdutoForm
from home.forms import VendaForm
from home.models import Pessoa
from home.models import Produto
from home.models import Venda
from home.forms import Estoque4peca
from home.forms import Estoque4pecaForm
from home.forms import Estoque1peca
from home.forms import Estoque1pecaForm
from django.core.validators import validate_email
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from home.filters import UserFilter
from home.filters import PessoaFilter
from home.filters import ProdutoFilter
from django.views import generic
from . import forms, models
from django_filters import rest_framework as filters
from django.db.models import Q
from django.core.paginator import Paginator




# /////////////////////////////////////////////////////////////////////////////////
# /////////////////////////////////////////////////////////////////////////////////
# /////////////////////////////////////////////////////////////////////////////////




#INICIAL VIEWS VIEWS ////////////////////////////////////////////////

def inicio(request):
    return render(request, 'inicio.html')

#PAGINA PRINCIPAL DOS MENUS

def principal(request):
    return render(request, 'principal.html')

# /////////////////////////////////////////////////////////////////////////////////
# /////////////////////////////////////////////////////////////////////////////////
# /////////////////////////////////////////////////////////////////////////////////

#PESSOA  VIEWS VIEWS ////////////////////////////////////////////////
#PESSOA  VIEWS VIEWS ////////////////////////////////////////////////
#PESSOA  VIEWS VIEWS ////////////////////////////////////////////////

#  FILTRO VIEWS  PESSOA ////////////////////////////////////////////////


def home(request):
    data = {}
    data['db'] = Pessoa.objects.all()

    if 'q' in request.GET:
        q = request.GET['q']

        data = Pessoa.objects.filter(nome__icontains=q )
        multiple_q = Q(Q(nome__icontains=q) | Q(endereco__icontains=q))
        data = Pessoa.objects.filter(multiple_q)

    else:
        data = Pessoa.objects.all()
    context = {
        'data' : data,
    }

    paginator = Paginator(data, 5)  # Show 25 contacts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'pessoa/index.html', {'data': page_obj})


    return render(request, 'pessoa/index.html', context)



def form(request):
    data = {}
    data ['form'] = PessoaForm()
    return render(request, 'pessoa/formpessoa.html', data)


def create(request):
    form = PessoaForm(request.POST or None)

    if form.is_valid():
        form.save()
    messages.success(request, 'Cliente Cadastrado Com Sucesso.')
    return redirect('home')

def view(request, pk):
    data = {}
    data['db'] = Pessoa.objects.get(pk=pk)
    return render(request, 'pessoa/viewpessoa.html', data)

def edit(request, pk):
    data = {}
    data['db'] = Pessoa.objects.get(pk=pk)
    data['form'] = PessoaForm(instance=data['db'])
    return render(request, 'pessoa/formpessoa.html', data)

def update(request, pk):
    data = {}
    data['db'] = Pessoa.objects.get(pk=pk)
    form = PessoaForm(request.POST or None, instance=data['db'])
    if form.is_valid():
        form.save()
    return redirect('home')

def delete(request, pk):
    db = Pessoa.objects.get(pk=pk)
    db.delete()
    return redirect('home')



#PRODUTO VIEWS VIEWS ////////////////////////////////////////////////
#PRODUTO VIEWS VIEWS ////////////////////////////////////////////////
#PRODUTO VIEWS VIEWS ////////////////////////////////////////////////

#  FILTRO VIEWS  PRODUTO ////////////////////////////////////////////////

def homeproduto(request):
    data = {}
    data['db'] = Produto.objects.all()

    if 'q' in request.GET:
        q = request.GET['q']
        #data = Produto.objects.filter(nome__icontains=q)
        multiple_q = Q(Q(produto__icontains=q) | Q(obs__icontains=q))
        data = Produto.objects.filter(multiple_q)

    else:
        data = Produto.objects.all()
    context = {
        'data' : data
    }
    return render(request, 'produto/index.html', context)



###############################################################################################
def formproduto(request):
    data = {}
    data ['form'] = ProdutoForm()
    return render(request, 'produto/formproduto.html', data)



def createproduto(request):
    form = ProdutoForm(request.POST or None)
    if form.is_valid():
        form.save()

    return redirect('homeproduto')


def viewproduto(request, pk):
    data = {}
    data['db'] = Produto.objects.get(pk=pk)
    return render(request, 'produto/viewproduto.html', data)

def editproduto(request, pk):
    data = {}
    data['db'] = Produto.objects.get(pk=pk)
    data['form'] = ProdutoForm(instance=data['db'])
    return render(request, 'produto/formproduto.html', data)

def updateproduto(request, pk):
    data = {}
    data['db'] = Produto.objects.get(pk=pk)
    form = ProdutoForm(request.POST or None, instance=data['db'])
    if form.is_valid():
        form.save()
    return redirect('homeproduto')

def deleteproduto(request, pk):
    db = Produto.objects.get(pk=pk)
    db.delete()
    return redirect('homeproduto')


#VENDA VIEWS VIEWS ////////////////////////////////////////////////
#VENDA VIEWS VIEWS ////////////////////////////////////////////////
#VENDA VIEWS VIEWS ////////////////////////////////////////////////


def homevenda(request):
    data = {}
    data['db'] = Venda.objects.all()


    if 'q' in request.GET:
        q = request.GET['q']
        data = Venda.objects.filter(placa__icontains=q)
        multiple_q = Q(Q(placa__icontains=q) | Q(carro__icontains=q) | Q(pessoa__nome__icontains=q))
        data = Venda.objects.filter(multiple_q)

    else:
        data = Venda.objects.all()

    context = {
        'data' : data,

    }
    return render(request, 'venda/index.html',  context)



def formvenda(request):
    data = {}
    data ['form'] = VendaForm()
    return render(request, 'venda/formvenda.html', data)

def createvenda(request):
    form = VendaForm(request.POST or None)
    if form.is_valid():
        form.save()

    return redirect('homevenda')

def viewvenda(request, pk):
    data = {}
    data['db'] = Venda.objects.get(pk=pk)
    return render(request, 'venda/viewvenda.html', data)

def editvenda(request, pk):
    data = {}
    data['db'] = Venda.objects.get(pk=pk)
    data['form'] = VendaForm(instance=data['db'])
    return render(request, 'venda/formvenda.html', data)

def updatevenda(request, pk):
    data = {}
    data['db'] = Venda.objects.get(pk=pk)
    form = VendaForm(request.POST or None, instance=data['db'])
    if form.is_valid():
        form.save()
    return redirect('homevenda')

def deletevenda(request, pk):
    db = Venda.objects.get(pk=pk)
    db.delete()
    return redirect('homevenda')

#ESTOQUE 4 PEÇA VIEWS VIEWS ////////////////////////////////////////////////
#ESTOQUE 4 PEÇA  VIEWS VIEWS////////////////////////////////////////////////
#ESTOQUE 4 PEÇA  VIEWS VIEWS////////////////////////////////////////////////

def homeestoque4peca(request):
    data = {}
    data['db'] = Estoque4peca.objects.all()
    return render(request, 'estoque4peca/index.html', data)

def formestoque4peca(request):
    data = {}
    data ['form'] = Estoque4pecaForm()
    return render(request, 'estoque4peca/formestoque4peca.html', data)

def createestoque4peca(request):
    form = Estoque4pecaForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('homeestoque4peca')

def viewestoque4peca(request, pk):
    data = {}
    data['db'] = Estoque4peca.objects.get(pk=pk)
    return render(request, 'estoque4peca/viewestoque4peca.html', data)

def editestoque4peca(request, pk):
    data = {}
    data['db'] = Estoque4peca.objects.get(pk=pk)
    data['form'] = Estoque4pecaForm(instance=data['db'])
    return render(request, 'estoque4peca/formestoque4peca.html', data)

def updateestoque4peca(request, pk):
    data = {}
    data['db'] = Estoque4peca.objects.get(pk=pk)
    form = Estoque4pecaForm(request.POST or None, instance=data['db'])
    if form.is_valid():
        form.save()
        return redirect('homeestoque4peca')

def deleteestoque4peca(request, pk):
    db = Estoque4peca.objects.get(pk=pk)
    db.delete()
    return redirect('homeestoque4peca')


#ESTOQUE PARCIAL VIEWS VIEWS ////////////////////////////////////////////////
#ESTOQUE PARCIAL VIEWS VIEWS ////////////////////////////////////////////////
#ESTOQUE PARCIAL VIEWS VIEWS ////////////////////////////////////////////////




def homeestoque1peca(request):
    data = {}
    data['db'] = Estoque1peca.objects.all()
    if 'q' in request.GET:
        q = request.GET['q']
        data = Estoque1peca.objects.filter(produto__icontains=q)
    else:
        data = Estoque1peca.objects.all()
    context = {
        'data' : data
    }
    return render(request, 'estoque1peca/index.html', context)

def formestoque1peca(request):
    data = {}
    data ['form'] = Estoque1pecaForm()

    return render(request, 'estoque1peca/formestoque1peca.html', data)


def createestoque1peca(request):
    if request.method == 'POST':
        form = Estoque1pecaForm(request.POST)
        if form.is_valid():
            form.save()
    form = Estoque1pecaForm()
    messages.success(request, 'Produto Criado com Sucesso.')
    return redirect('homeestoque1peca')


def viewestoque1peca(request, pk):
    data = {}
    data['db'] = Estoque1peca.objects.get(pk=pk)
    return render(request, 'estoque1peca/viewestoque1peca.html', data)

def editestoque1peca(request, pk):
    data = {}
    data['db'] = Estoque1peca.objects.get(pk=pk)
    data['form'] = Estoque1pecaForm(instance=data['db'])

home/templates/venda/formvenda.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block conteudo %}
{% load static %}
{% load crispy_forms_tags %}

<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Crud com Python</title>
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />

</head>
<body>

<div class="col-8 m-auto pt-2 pb-2 text-center">
    <h1>Cadastrar Vendas</h1>
</div>

<br><br>
<div class="col-8 m-auto pt-2 pb-2  text-center">
    <a href="/principal" class="btn btn-secondary btn-lg">Pagina Principal</a>
</div>

<div class="col-18 m-auto pt-20 pb-20  text-right">
    <a href="/homevenda" class="btn btn-primary btn-lg">Voltar</a>
</div>

<div class="col-50 m-auto pt-13 pb-12  text-center">
    <div id="result"></div>

      <div class="col-8 m-auto pt-4 pt-2 text-center"></div>
        <form  name="formvenda" id="formvenda" action="{% if db %}/updatevenda/{{db.id}}/{%else%}/createvenda/{% endif %}" method="post">
            {% csrf_token %}
            <!--{{form.as_p}}-->
            {{ form|crispy }}

<input type="submit" class="btn btn-success" value="Salvar">
 </form>
</div>

<script>

$(document).ready(function() {
     $('#id_pessoa.select.form-control').select2();
});

</script>
<script>

$(document).ready(function() {
     $('#id_produto.select.form-control').select2();
});

</script>

<script>

$(document).ready(function() {
     $('#id_pag').select2();
});

</script>

{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

</body>
</html>

home/templates/venda/index.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block conteudo %}
{% load static %}

<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Cadastrar Venda</title>
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body>

<div class="col-8 m-auto pt-2 pb-2 text-center">
    <h1>Vendas</h1>
</div>

       <h5> Pesquisar Vendas</h5>

  <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" name="q" type="search" placeholder="Buscar" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
      </form>

<br><br>

<div class="col-8 m-auto pt-2 pb-2 text-center">
<a href="/formvenda" class="btn btn-success btn-lg">Adicionar</a>
</div>
<div class="col-18 m-auto pt-20 pb-20  text-right">
    <a href="/principal" class="btn btn-primary btn-lg">Voltar</a>
</div>


<div class="table-responsive">
    <table class="table table-striped" border="9" style="width:100%" >
<thead>

   <tr class="table-active ">

      <th scope="col">ID</th>
       <th scope="col">Titulo</th>
      <th scope="col">Cliente</th>
        <th scope="col">Produto</th>
        <th scope="col">Placa</th>
        <th scope="col">Carro</th>
        <th scope="col">Data_venda</th>
        <th scope="col">Preço</th>
        <th scope="col">venc fatura</th>
        <th scope="col">Pagamento</th>






       <th width="col">+DETALHES</th>
       <th scope="col">EDITAR</th>
       <th scope="col">DELETAR</th>
    </tr>

  </thead>

  <tbody>


  {% for data in data %}
    <tr>

      <th> {{data.id}}</th>
      <th> {{data.titulo}}</th>
        <td>{{data.pessoa}}</td>
        <td>{{data.produto}}</td>
        <td>{{data.placa}}</td>
        <td>{{data.carro}}</td>
        <td>{{data.data_venda}}</td>
        <td>R${{data.preco}}</td>
        <td>{{data.venc_fatura| date:'d/m/Y'}}</td>
        <td>{{data.pag}}</td>









             <td> <a href="/viewvenda/{{data.id}}/" class="btn btn-dark btn-sm">+Detalhes</a></td>
           <td> <a href="/editvenda/{{data.id}}/" class="btn btn-primary btn-sm">Editar</a></td>
           <td> <a href="/deletevenda/{{data.id}}/" class="btn btn-danger btn-sm btnDel">Deletar</a></td>

 </tr>




    {% endfor %}

  </tbody>

</table>

</div>









<script src="{% static 'javascript.js' %}"></script>

</body>
</html>

{% endblock %}

home/templates/venda/viewvenda.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block conteudo %}
{% load static %}

<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Vizualização Vendas</title>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<br>

<body>

<div class="col-8 m-auto pt-2 pb-2 text-center">
    <h4>{{ db.pessoa }}</h4>
</div>

<div class="col-18 m-auto pt-2 pb-2  text-center">
    <a href="/principal" class="btn btn-secondary btn-lg">Pagina Principal</a>
</div>

<div class="col-18 m-auto pt-20 pb-20  text-right">
    <a href="/homevenda" class="btn btn-primary btn-lg">Voltar</a>
</div>





<div class="table-responsive">
  <table class="table table-striped" border="9" style="width:100%" >

<tr class="table-dark">
  <th> Descrição</th>  
  <td>{{ db.titulo }}</td>
  </tr>

  <tr class="table-active">
  <th> Cliente</th>  
  <td>{{db.pessoa}}</td>
  </tr>

  <tr>
  <th> Produto</th>  
  <td>{{db.produto}}</td>
  </tr>

  <tr class="table-active">
  <th> placa</th>  
  <td>{{db.placa}}</td>
  </tr>

  <tr>
  <th> Carro</th>  
  <td>{{db.carro}}</td>
  </tr>

  <tr class="table-active">
  <th> Preço</th>  
  <td>{{db.preco}}</td>
  </tr>


  <tr class="table-active">
  <th> Pagamento</th>  
  <td>{{db.Pagamento}}</td>
  </tr>

  <tr class="table-active">
    <th> Observação</th>  
    <td>{{db.obs}}</td>
    </tr>


    <tr>

  <td> <a href="/editvenda/{{db.id}}/" class="btn btn-primary btn-sm">Editar</a></td>
   </tr>

  
  <tr>
  <div class="col-1 m-auto pt-20 pb-1  text-center">
  <td> <a href="/deletevenda/{{db.id}}/" class="btn btn-danger btn-sm btnDel">Deletar</a>  </td>
   </tr>
  </div>

</table>
</div>






<script src="{% static 'javascript.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>
</html>
{% endblock %}